# Generated by Django 3.1 on 2020-08-20 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200820_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100), unique=True, verbose_name='URL Slug'),
        ),
    ]
