# Generated by Django 3.1 on 2020-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20200820_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>', unique=True, verbose_name='URL Slug'),
        ),
    ]
