# Generated by Django 3.1 on 2020-08-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20200820_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='title', unique=True, verbose_name='URL Slug'),
        ),
    ]
