# Generated by Django 3.1 on 2020-08-20 17:52

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20200820_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title'),
        ),
    ]
